export const ErrorCodes = {
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_NUMBER_ALREADY_EXISTS: 'ACCOUNT_NUMBER_ALREADY_EXISTS',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  DB_UNIQUE_VIOLATION: 'DB_UNIQUE_VIOLATION',
  DB_ERROR: 'DB_ERROR',
  UNEXPECTED: 'UNEXPECTED',
  TRANSFER_SAME_ACCOUNT: 'TRANSFER_SAME_ACCOUNT',
  ACCOUNT_NOT_OWNED: 'ACCOUNT_NOT_OWNED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
