version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d bank']
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: bank
    command: >
      sh -c '
        for i in $(seq 1 30); do
          pg_isready -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" && break;
          echo "⏳ esperando postgres..."; sleep 2;
        done
        npx typeorm-ts-node-commonjs migration:run -d src/infra/config/typeorm.datasource.ts
      '
    restart: 'no'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: bank
      JWT_SECRET: supersecret
    ports:
      - '3000:3000'
    command: ['node', 'dist/src/main.js']

volumes:
  pgdata:
