name: CI
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bankapp
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres -d bankapp"
          --health-interval=5s --health-timeout=3s --health-retries=10
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: bankapp
      JWT_SECRET: testsecret
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: nnpm ci --include=dev --ignore-scripts
      - run: npm run build
      - name: Run migrations (opcional)
        run: |
          if npm run | grep -q "migrate:run"; then
            npm run migrate:run
          else
            echo "No migration script found, skipping"
          fi
      - run: npm test
